database:
  image: "mysql:5.7"
  command: "mysqld --init-file=/tmp/db/create_database.sql"
  ports:
    - "13306:3306"
  volumes:
    - "./db:/tmp/db"
    - "./db/conf.d:/etc/mysql/conf.d"
  environment:
    MYSQL_ROOT_PASSWORD: "root"
