version: "3.3"
services:
  mysql:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: "lekcije"
      MYSQL_USER: "lekcije"
      MYSQL_PASSWORD: "lekcije"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "13306:3306"
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./volume/mysql/etc/mysql:/etc/mysql"
#      - ./log/mysql:/var/log/mysql

  redis:
    image: "redis:3.2-alpine"
    ports:
      - "16379:6379"
