version: "2"
services:
  mysql_data:
    image: busybox
    volumes:
      - "./db:/tmp/db"
      - "./volume/mysql/etc/mysql:/etc/mysql"
      #- "./volume/mysql/var/lib/mysql:/var/lib/mysql"
    container_name: lekcije_mysql_data

  mysql:
    image: "mysql:5.7"
    command: "mysqld --init-file=/tmp/db/create_database.sql"
    ports:
      - "13306:3306"
    volumes_from:
      - mysql_data
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  redis:
    image: "redis:3.2-alpine"
    ports:
      - "16379:6379"
