
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[metadata.heroku]
  root-package = "github.com/oinume/lekcije"
  go-version = "go1.11"
  install = [ "./server/cmd/..." ]
  ensure = "true"
#  additional-tools = ["github.com/mattes/migrate"]

[[constraint]]
  name = "github.com/Songmu/retry"
  branch = "master"

[[constraint]]
  name = "github.com/fukata/golang-stats-api-handler"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/google/uuid"
  branch = "master"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.4.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  branch = "master"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  revision = "85774eb9dab486c4f0568df98fe5ad9ce7d4f75b"

[[constraint]]
  name = "github.com/jpillora/go-ogle-analytics"
  branch = "master"

[[constraint]]
  name = "github.com/oinume/goenum"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/profile"
  version = "1.2.0"

[[constraint]]
  name = "github.com/rs/cors"
  branch = "master"

[[constraint]]
  name = "github.com/sclevine/agouti"
  branch = "master"

[[constraint]]
  name = "github.com/sendgrid/rest"
  version = "v2.4.0"

[[constraint]]
  name = "github.com/sendgrid/sendgrid-go"
  version = "v3.4.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/stvp/rollbar"
  branch = "master"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.7.1"

[[constraint]]
  name = "goji.io"
  source = "github.com/goji/goji"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "543e37812f10c46c622c9575afd7ad22f22a12ba"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "golang.org/x/text"
  branch = "master"

#[[constraint]]
#  name = "google.golang.org/api"
#  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  name = "gopkg.in/redis.v4"
  source = "github.com/go-redis/redis"
  version = "v4.2.4"

[[constraint]]
  name = "gopkg.in/xmlpath.v2"
  source = "github.com/go-xmlpath/xmlpath"
  branch = "v2"

[[constraint]]
  name = "cloud.google.com/go"
  version = "v0.26.0"

[[override]]
  name = "github.com/googleapis/gax-go"
  revision = "de2cc08e690b99dd3f7d19937d80d3d54e04682f"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"
