name: backend
on:
  push:
    paths:
      - "**.go"
      - "**.json"
      - "**.html"
      - "**.proto"
      - "**.ya?ml"
      - "**.sh"
      - "**.py"
      - "**.ya?ml"
      - "go.mod"
      - "go.sum"
      - "Makefile"
env:
  CACHE_VERSION: 1
  GOPATH: /home/runner/go
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis:3.2-alpine # TODO: Update to latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      ENABLE_TRACE: "false"
      GO111MODULE: "on"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: "lekcije"
      MYSQL_PASSWORD: "lekcije"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "lekcije_test"
      MYSQL_DATABASE_TEST: "lekcije_test"
      REDIS_URL: "redis://h:@127.0.0.1:6379"
      E2E_WEB_DRIVER: "PhantomJS"
      VERSION_HASH: "_version_"
      NODE_ENV: "test"
      LEKCIJE_ENV: "test"
    timeout-minutes: 20
    steps:
      - name: Print PWD
        run: |
          pwd
      - name: Set up Go 1.15
        id: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Redis cli
        run: |
          sudo apt install redis-tools
          redis-cli ping
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.GOPATH }}/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}-${{ env.CACHE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install tools
        run: |
          ls -l $GOPATH/bin || true
          if [ ! -e $GOPATH/bin/goose ]; then
            make install-tools
          fi
      - name: Build
        run: |
          make backend/build
      - name: Run go/lint
        run: |
          export PATH=${PATH}:${GOPATH}/bin
          make go/lint
      - name: Create database
        run: |
          mysql -h${MYSQL_HOST} -uroot -proot < ./db/docker-entrypoint-initdb.d/create_database.sql
      - name: Apply database migrations
        run: |
          export PATH=${PATH}:${GOPATH}/bin
          make test/db/goose/up
      - name: Run go/test
        run: |
          export
          make go/test GO_TEST="go test -v -race -coverprofile=coverage.txt -covermode=atomic -p=1"
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: false
      #          flags: unittests # optional
      #          name: codecov-umbrella # optional

  deploy-to-production:
    name: deploy to production
#    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
#      - name: Save credentials into secrect.yaml
#        run: |
#          sed "s/<SENDGRID_API_KEY>/$SENDGRID_API_KEY/" ./entrypoint/task/secret.yaml.tmpl > ./entrypoint/task/secret.yaml
#        env:
#          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.GOPATH }}/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}-${{ env.CACHE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install App Engine Go SDK
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-app-engine-go
      - name: Initialize Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          export_default_credentials: true
      - name: Run go mod vendor
        run: |
          go mod vendor
      - name: Deploy
        run: |
          GO111MODULE=off gcloud app deploy --project ${{ secrets.GCP_PROJECT_ID }} --no-promote --quiet ./appengine/app.yaml
